// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9qB7Kc5-fI1VYgo0t9E3fV5KB6OF7SAU',
    appId: '1:475220792855:web:c3fc6edd3da3526875ee52',
    messagingSenderId: '475220792855',
    projectId: 'medease-52e61',
    authDomain: 'medease-52e61.firebaseapp.com',
    storageBucket: 'medease-52e61.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEDC_m__WJ5tdrvq4TD2RcK0omZacZVl8',
    appId: '1:475220792855:android:5235c21f94d5f24775ee52',
    messagingSenderId: '475220792855',
    projectId: 'medease-52e61',
    storageBucket: 'medease-52e61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgw5YNxG3DEFxd07U7Fa8iA0IZ9fT6djo',
    appId: '1:475220792855:ios:40f92a12c887b09975ee52',
    messagingSenderId: '475220792855',
    projectId: 'medease-52e61',
    storageBucket: 'medease-52e61.appspot.com',
    iosBundleId: 'com.example.hack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgw5YNxG3DEFxd07U7Fa8iA0IZ9fT6djo',
    appId: '1:475220792855:ios:eec34b5318af7e1975ee52',
    messagingSenderId: '475220792855',
    projectId: 'medease-52e61',
    storageBucket: 'medease-52e61.appspot.com',
    iosBundleId: 'com.example.hack.RunnerTests',
  );
}
